// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAOKei960WvE77flTuRE6nWnbuZnjcGGY',
    appId: '1:926512925301:web:d7c5fc1353895e6b0c863c',
    messagingSenderId: '926512925301',
    projectId: 'karsaazi-cf8a4',
    authDomain: 'karsaazi-cf8a4.firebaseapp.com',
    storageBucket: 'karsaazi-cf8a4.firebasestorage.app',
    measurementId: 'G-JP254K4JXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-IuxlqrmVk27WJM8EpsVCpnL15SnYlLU',
    appId: '1:926512925301:android:1a4e417f68b752fb0c863c',
    messagingSenderId: '926512925301',
    projectId: 'karsaazi-cf8a4',
    storageBucket: 'karsaazi-cf8a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_YFmeMg9hX0nz9RV34-egxyTmak1XuVo',
    appId: '1:926512925301:ios:b23b75748e015ec70c863c',
    messagingSenderId: '926512925301',
    projectId: 'karsaazi-cf8a4',
    storageBucket: 'karsaazi-cf8a4.firebasestorage.app',
    androidClientId: '926512925301-fvv0g68647t58a5l5rupoium721r2jm4.apps.googleusercontent.com',
    iosClientId: '926512925301-l3um0ro6griq9hik4tjr4jb2cr29vdl4.apps.googleusercontent.com',
    iosBundleId: 'com.hunarmand.hunarmand',
  );
}
