name: Flutter APK Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Install Dependencies
        run: flutter pub get
      
      # ✅ Gradle memory fix
      - name: Set Gradle JVM Args
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m" >> ~/.gradle/gradle.properties
      
      - name: Build Release APK
        run: flutter build apk --release
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: karsaazi-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
